### PR TITLE
Use C++17-compatible ome::compat::variant

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
See https://github.com/ome/ome-common-cpp/pull/57

### CODE REVIEW

**Comment by joshmoore** [comment]
Currently, I think I'd be in favor of removing the lines rather than echo'ing them, but that quickly brings me to removing the dockerfile. Anyone have an opinion on whether to do that now or a follow-up once https://github.com/ome/ome-files-build/pull/1 is actioned?

**Comment by rleigh-codelibre** [comment]
Moving the Dockerfile to ome-files-build looks appropriate and removes all the downsides of having them in  individual repositories like this one, where they cause problems.  I can update the PRs to drop these Dockerfiles entirely.

**Comment by joshmoore** [comment]
Looking at this, I assume we want to save the run_checks script somewhere, and the flake8'ing can likely also still occur in travis.

**Comment by joshmoore** [comment]
flake8-only travis is now green. Merging. I'll look into including a call to run_checks in https://github.com/ome/ome-files-build/pull/1

**Comment by rleigh-codelibre** [comment]
@joshmoore Doesn't the resurrection of the script still retain the dependency on a fixed version of the ome-files-cpp build, which was the reason for removing it in the first place?  Shouldn't this be restricted to flake8 **only**, leaving the other checks to ome-files-build?

**Comment by joshmoore** [comment]
I don't think so, but I might be missing something. If you mean that the _running_ of the checks should be left to ome-files-build, then definitely. If you mean the _code_ for the check should be there, too, then perhaps, but I wasn't ready to go that far yet.

**Comment by rleigh-codelibre** [comment]
`docker exec omefilespy` in the `.travis/run_checks` script.  Isn't that a container with an ome-files-cpp build in it?  Where is it now created.  It's going to be outdated isn't it?  That's what I think should not be in this repository because it's not going to match the current real state of ome-files-cpp and the other repositories.

**Comment by joshmoore** [comment]
Definitely agreed. There will need to be another PR to remove the execution in Docker and likely use `.` rather than the hard-coded `/git/ome-files-py` but I haven't progressed far enough for either of those decisions to be made.

**Pull request merged**
