### PR TITLE
Methods related to plane coordinates

### PR DESCRIPTION
**Pull request by simleo**
Adds bindings for:

* `getIndex`
* `getZCTCoords`
* `getDimensionOrder`

### CODE REVIEW

**Comment by simleo** [comment]
Note that in the unit test for `get_zct_coords` I'm not asserting that the method throws if the given index is too big, because this is currently not checked for in the C++ implementation. See https://github.com/ome/ome-files-cpp/pull/65.

**Comment by rleigh-codelibre** [comment]
This all looks good, and the builds are green, so looks good to merge.  With https://github.com/ome/ome-files-cpp/pull/65 being open, it should be fine to add any missing assertions since the CI will test this.

If these wrapped methods return NULL, does this get automatically converted into a Python Error exception?

**Comment by simleo** [comment]
Discussed with @sbesson: adding the missing assert now might break the Docker build, so we'll postpone for now.

**Comment by simleo** [comment]
> If these wrapped methods return NULL, does this get automatically converted into a Python Error exception?

The return value that signals an error condition is either NULL or -1 depending on the function (most of the times it's NULL). The resulting exception on the Python side depends on the error condition set previously. In some cases you have to do it explicitly, by calling `PyErr_SetString`. If you want to generate an exception because what failed is already in the Python API, however, an error condition has already been set (e.g., when `PyArg_ParseTuple` fails you just return null, because the appropriate error condition has already been set).

Ref: https://docs.python.org/2/c-api/intro.html#exceptions

**Pull request merged**
