### PR TITLE
Add bindings for model enums

### PR DESCRIPTION
**Pull request by simleo**
Manually adds the binding code generated with https://github.com/ome/ome-model/pull/46 and tests it.

We probably don't want to merge this PR as it is, but rather create an `ome-model-py` package and add it as a dependency. Note that this PR also contains some simple Python code generation. This could be done in `ome-model` by adding a new Python language class and providing appropriate templates. I haven't done this in https://github.com/ome/ome-model/pull/46 to keep its impact on the existing code minimal.

Example:

```python
In [5]: from ome_files.enums import Pulse

In [6]: Pulse.__members__
Out[6]: 
{'CW': enum_value.CW,
 'MODELOCKED': enum_value.MODELOCKED,
 'OTHER': enum_value.OTHER,
 'QSWITCHED': enum_value.QSWITCHED,
 'REPETITIVE': enum_value.REPETITIVE,
 'SINGLE': enum_value.SINGLE}

In [7]: p = Pulse(Pulse.SINGLE)

In [8]: p.values()
Out[8]: 
{enum_value.CW: 'CW',
 enum_value.SINGLE: 'Single',
 enum_value.QSWITCHED: 'QSwitched',
 enum_value.REPETITIVE: 'Repetitive',
 enum_value.MODELOCKED: 'ModeLocked',
 enum_value.OTHER: 'Other'}

In [9]: p == Pulse("Single")
Out[9]: True

In [12]: p.value
Out[12]: enum_value.SINGLE
```

--breaking

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
@sbesson Can now be unexcluded now devtoolset-4 is on cowfish.  Likewise ome-files-py can be re-enabled in the job.

**Comment by sbesson** [comment]
The Travis C7 failure as well https://hub.docker.com/r/snoopycrimecop/ome-files-py-c7/builds/bmje2ikct9ptf66uogdzmt5 are likely related to the issue discussed extensively https://trello.com/c/5UxvgXm1/6-ome-files-python-pybind11.
Next step here is probably to update the base OME Files C++/C7 image (https://github.com/openmicroscopy/ome-files-cpp-c7-docker) to activate devtoolset-4.

**Comment by rleigh-codelibre** [comment]
@sbesson The TIFF wrapping is based upon this branch to avoid conflicts with both the setup.py changes and the Dockerfile changes.  That can be rebased, but it would still conflict with this.  Ideally, we would merge this quickly so we can continue with the other stuff.

**Comment by simleo** [comment]
> Ideally, we would merge this quickly so we can continue with the other stuff

Actually this was just meant to test the code generated by https://github.com/ome/ome-model/pull/46. Eventually, `ome-files-py` should probably depend on `ome-model`, as suggested in the PR description.

**Comment by sbesson** [comment]
Thanks for the initial investigation @simleo. 
For the immediate priorities, we will be looking into wrapping of the OME-TIFF writers to support passing OME-XML metadata as a string. Closing this PR as more work will be needed and it will conflict. As mentioned in the PR description and https://github.com/ome/ome-files-py/pull/23#issuecomment-337668440, we will probably need to discuss the packaging of the `ome-model-py` module when resurrecting the wrapping of the model classes. I will create a card capturing this.

**Pull request closed without merging**
