### PR TITLE
Add OME-TIFF writer

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
Note: Based on @simleo 's branch for adding model enums to avoid conflicts.

Changes:

- `type()` method renamed to `dtype()` so that we can use `type()` with the model enum type in a followup change to match the OME Files C++ API.
- OMETIFFReader `open_bytes` returns a 9D `ndarray` rather than a byte array, to match the OME Files C++ interface.  This makes it easier to interoperate with Python.
- OMETIFFReader `open_array` renamed to `open_array_simple` (because it returns a 2D ndarray subsetted from the 9D array, or a list of 2D arrays for RGB data).  Could also be named `open_bytes_simple` or similar.
- Add OMETIFFWriter; this contains `save_bytes` and `save_array_simple` to match the reader API
- The writer supports all pixel types and data layouts
- The reader does zero copies of pixel data (wraps the pixel buffer directly) but the writer has to copy the pixel values between the ndarray and pixel buffer; this is because the layout of ndarray dimension order can't be determined exactly from the strides.  The pixel buffer has explicit ordering plus computed strides; ndarray only has strides making it impossible to determine the ordering.
- Use `PYBIND11_MODULE` in place of `PYBIND11_PLUGIN` [deprecated]
- Tests converted to use pytest to match what the rest of the project's Python code is using, and to allow the use of parameterised tests

Testing:

Build with `python setup.py build_ext -I /<files>/include -L /<files>/lib && python setup.py install
Test with `cd test; python -m pytest`

The writer tests will output an `rgb.ome.xml` (uint8) and a `grey.ome.xml` (float).  You can open with `showinf` to verify them.  Note: use `-fast -autoscale` for the grey float data.

@simleo I hope this is OK with you; this was my first use of pybind11 and python for a long time.  If you have the time to look over it, I'd be very appreciative of any suggestions you have for improving it.

A couple of questions:

Why is `open_array` returning a list of 2D arrays rather than a 3D array when dealing with RGB data?  Could we convert this to use 3D arrays, or is this for use with specific APIs which require lists of 2D arrays?  Could the user reshape the array themselves if this is the case?

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
Note https://github.com/ome/ome-cmake-superbuild/pull/168 for updating pybind11

**Comment by simleo** [comment]
> If you have the time to look over it, I'd be very appreciative of any suggestions you have for improving it.

I should be able to take a look this weekend

> Why is `open_array` returning a list of 2D arrays rather than a 3D array when dealing with RGB data?

This method was factored out from the `dump_planes.py` example, so it's just returning what `libtiff` expects

> Could we convert this to use 3D arrays, or is this for use with specific APIs which require lists of 2D arrays? Could the user reshape the array themselves if this is the case?

Yes, the method should return what makes most sense in the general case and consumers (including `dump_planes.py`) can convert as needed.

**Comment by dgault** [comment]
The installation completed and all tests ran and passed using pytest. The test files grey.ome.tiff and rgb.ome.tiff are correct and valid. Generally the code looks to be good and the new enums and writer are all behaving as expected.

The following tests were run:

`test_enums.py ................................
test_metadata.py ...
test_omefiles.py .
test_ometiffreader.py .................................................
test_ometiffwriter.py ....
========================== 89 passed in 2.15 seconds ===========================
`

The modified tests all look good and are running the tests as previous. The newly added enum, reader and writer tests look to be providing appropriate coverage of the enum classes.

Changing type to dtype seems sensible to free up the use type later. The use of ndarray to match the OME Files C++ API and pytest to match the rest of the project also makes sense and looks good.

If I had a preference I would tend to prefer the naming open_bytes_simple rather than open_array_simple as it returns a subset of open_bytes. Same would apply for save_array_simple. The name open_array_simple is also acceptable however.

For get_pixel_dtype, PixelType::BIT returns "?" now instead of "b1", im assuming thats simply because it does not currently handle bit pixel types?

The python 3.3 build in Travis is currently failing, apparently during test_ometiffreader, so far I ahve been unable to figure out exactly why though.

**Comment by rleigh-codelibre** [comment]
@dgault I'll rename the "simple" methods.

For the travis failure, it's python 2.7 failing despite the "3.3" label.  It's reproducible with a local docker image, but since the ome-files build in the parent image has no debug info I've not yet determined why it happens.

**Comment by sbesson** [comment]
With https://github.com/ome/ome-files-py/pull/26 included, an extra commit is needed to fix the conflict. Hopefully this will help better identifying the failing configurations and prevent the confusion highlighted in https://github.com/ome/ome-files-py/pull/25#issuecomment-338699600.
 As mentioned in https://github.com/ome/ome-files-py/pull/25#pullrequestreview-71027929, can you also force push 19458ea away since more design/work will be required to properly add the model bindings.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OME-FILES-CPP-DEV-merge-push-superbuild#784](https://ci.openmicroscopy.org/job/OME-FILES-CPP-DEV-merge-push-superbuild/784/). See the [console output](https://ci.openmicroscopy.org/job/OME-FILES-CPP-DEV-merge-push-superbuild/784/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - Dockerfile.u1604
    - Dockerfile.c7

--conflicts

**Comment by rleigh-codelibre** [comment]
I've rebased this work on top of the latest master, since there were a lot of messy conflicts to resolve.  I've fixed all the points mentioned.

The travis docker usage seems to be very flaky.  And I think there's additionally an issue with the c7 image which I can reproduce on beluga, but I don't understand why it's happening.  If anyone has any idea what's up with this, I'd be very interested.  Likewise, has docker been this flaky in the past, hanging while updating?  Is it robust enough to use for CI testing with travis?

**Comment by sbesson** [comment]
@rleigh-codelibre might be related to https://www.traviscistatus.com/incidents/v4jnp6nkgzqx ?

**Comment by rleigh-codelibre** [comment]
@sbesson For the timeouts, looks like it.  Do we have to use docker hub, or are there alternatives?

**Comment by sbesson** [comment]
Timeouts seem to be resolved now. Re Docker Hub, it is the default Docker registry and we have been successfully using it across our organizational repos notably in Travis for testing.

Coming back to the C7 failures and https://github.com/ome/ome-files-py/pull/25#issuecomment-338699600, what are the next steps to troubleshoot? Are there changes to open against the [base image](https://github.com/openmicroscopy/ome-files-cpp-c7-docker)?

**Comment by rleigh-codelibre** [comment]
The base image shouldn't need any changes.  We could try building it using devtoolset-4, but that shouldn't be a requirement (worked without when I tested in a CentOS 7 VM).  I could reproduce on beluga, but it's still not clear to me why it fails.

The docker image is also not doing a debug build; that hinders debugging.  Needs `CXXFLAGS=-g3` in the environment and `CMAKE_BUILD_TYPE=Debug` for cmake.  Also, the hack to ld.so.conf/ldconfig should be unnecessary if we build separate packages rather than using the superbuild.  The superbuild isn't really intended for system-wide installation into /usr[/local] due to it making some assumptions about paths which are wrong here.  We use `lib` as the libdir so that our packaged builds are the same across all platforms, but centos is using `lib64`.  Other platforms alter the behaviour if you use /usr as a prefix; there aren't universally good choices here unfortunately.

**Comment by dgault** [comment]
The rebased code changes look good and testing the PR locally the installation completed and all tests ran and passed using pytest. With the devtoolset-4 changes from https://github.com/openmicroscopy/ome-files-cpp-c7-docker/pull/4 all of the builds and tests are now green. PR should be good to merge.

**Comment by joshmoore** [comment]
Thanks, @dgault. Proposed tag of `0.2.0`?

**Comment by joshmoore** [comment]
No objections. I'll move forward with the release of `0.2.0` ASAP.

**Pull request merged**
