### PR TITLE
Test Ubuntu and CentOS 7 in Travis

### PR DESCRIPTION
**Pull request by sbesson**
Follow up of https://github.com/openmicroscopy/ome-files-cpp-c7-docker/pull/3, this enables C7 Docker builds on `ome-files-py`:

- Add Dockerfile for CentOS7 based one ome-files-cpp-c7
- Move Dockerfiles under docker/${PLATFORM}
- Extend .travis.yml to test multiple environments

### CODE REVIEW

**Comment by sbesson** [comment]
@simleo: one question re the existing `.travis.yml` which includes had a Python 2.7/3.3 matrix. My reading from the existing Ubuntu 16.04 `Dockerfile` (and now the CentOS 7 one) is that the installation and tests of `ome-files-py` are executed for both Python 2 and Python3 within each container. Does that make these matrix components redundant so that we could simplify the matrix to `Ubuntu 16.04` and `CentOS 7` only?

**Comment by simleo** [comment]
The Python matrix is still relevant for the flake8 check. That could also be moved to the Dockerfile, although it would feel a bit out of place. Not sure if there's a way to apply a matrix only to a subset of the checks.

**Comment by sbesson** [comment]
@simleo https://github.com/ome/ome-files-py/pull/24/commits/31b224e1ac8ec8a61a9a9b5a59bdc2b241341b48 should limit the matrix combinations to only 2 while preserving the testing. In the meantime, I realized that the renaming will break https://hub.docker.com/r/snoopycrimecop/ome-files-py/.

A related step here would be to set up two Docker Hub repositories `ome-files-py-c7` and `ome-files-py-u1604`consuming different Docker locations in this project and probably deprcated `openmicroscopy/ome-files-py` as I don't think Hub handles renaming at the moment. /cc @joshmoore

**Comment by sbesson** [comment]
The initial solution to create platform-specific directories withe a `Dockerfile` do not integrate with the Docker Hub as the `Docker Location` parameter also changes the context in addition to specifying a custom `Dockerfile`.
https://github.com/ome/ome-files-py/pull/24/commits/b785b5aa49e5246918eb9aae76090a3450d63882 updates the strategy by moving both Dockerfiles back to the top-level directory instead, suffixes them with the platform and two Docker Hub repositories have been set up which consume `/Dockerfile.c7` and `/Dockerfile.u1604` - see https://hub.docker.com/r/snoopycrimecop/ome-files-py-c7/builds/brhu3yybiagzddqjgmwbm5b/ and https://hub.docker.com/r/snoopycrimecop/ome-files-py-u1604/builds/.

**Comment by dgault** [comment]
The merge daily builds for the below are now all building successfully:
https://hub.docker.com/r/openmicroscopy/ome-files-py/builds/
https://hub.docker.com/r/snoopycrimecop/ome-files-py-c7/builds/
https://hub.docker.com/r/snoopycrimecop/ome-files-py-u1604/builds/

The travis build is also green and has successfully run for both the c7 and u1604 platforms, the logs files for each look good.

**Comment by sbesson** [comment]
Thanks @dgault. If no objection with the layout and naming, I would propose to merge this PR and deprecate http://hub.docker.com/r/openmicroscopy/ome-files-py/ in favor of http://hub.docker.com/r/openmicroscopy/ome-files-py-u1604 and http://hub.docker.com/r/openmicroscopy/ome-files-py-c7.

**Pull request merged**
