### PR TITLE
Python extension: initial stub

### PR DESCRIPTION
**Pull request by simleo**
See ome/ome-files-cpp#41 for the initial discussion.

Exposes `OMETIFFReader` to the Python level. Only a subset of the API is available for now, see `test/test_ome_tiff.py` and `examples/dump_planes.py`.

Note that the Python naming convention for methods makes error messages misleading:

```
>>> import ome_files
>>> reader = ome_files.OMETIFFReader()
>>> reader.get_image_count()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ome_files.Error: Current file should not be null; call setId() first
>>> reader.set_id("multi-channel-4D-series.ome.tif")
[...]
```

I.e., the message (directly forwarded from the C++ exception) prompts for a `setId` call, while the method is called `set_id` in the Python version of the class. We could use the same method names as ome-files-cpp in spite of the convention, or generate new error messages that are consistent with the new method names.

### CODE REVIEW

**Comment by sbesson** [comment]
A couple of high-level questions coming back to this PR:

- what is the strategy for integrating this component in our CI infrastructure and distributing builds to the team for review? In recent discussion, @rleigh-codelibre mentioned integrating this repository into the superbuild. Is that still the preferred solution? If so, what are the next steps at the source code and the CI level?

- with regard to testing, I have some concerns with starting to embedd binary files like OME-TIFF into the source code repository. Any thought on whether these should be set up as integration tests. Alternatively, would there be a case for deriving and exposing some OME Files C++ functionality allowing to generate a subset of OME-TIFF files for testing?

**Comment by simleo** [comment]
I also don't like binary files in git repos. It was just the fastest way to provide some initial testing. Once we expose at lest part of writer functionality we should be able to generate test images on the fly.

**Comment by simleo** [comment]
febedd85c664462b6ab765d7e5fdd9f0f359b788 fixes a macOS problem where distutils passes runtime library paths using `-L` instead of `-rpath`. Unfortunately distutils has no support for plugging in custom compiler classes (like it does for commands).

**Comment by sbesson** [comment]
Coming back to https://github.com/ome/ome-files-py/pull/2#issuecomment-271355458, the biggest concern is the multi-channel OME-TIFF which is 8MB. Is the exact pixel data actually tested or are we checking the dimensions/types of the returned bytes? If the latter, I would be inclined to use a companion OME-TIFF fileset using a single TIFF for all planes, use it for testing (and force push away the commit with the 8MB file). Happy to derive such a sample if this makes sense and you provide me the minimal specifications in terms of dimensions etc

**Comment by simleo** [comment]
Exact pixel data is not tested. The `open_bytes` test only checks the number of bytes.

Other tests are about various bits of core metadata, i.e.:

```
SERIES_COUNT = 1
IMAGE_COUNT = 105
SIZE_X = 439
SIZE_Y = 167
SIZE_Z = 5
SIZE_T = 7
SIZE_C = 3
BYTES_PER_PIXEL = 1
PIXEL_TYPE = int8
RGB_CHANNEL_COUNT = 1
INTERLEAVED = False
```

**Comment by sbesson** [comment]
See https://gist.github.com/sbesson/666bb507580accaccab7b944f1fff243 for an example of 5D companion file (276K)

**Comment by simleo** [comment]
@seb I've tried that but I get warnings on set_id (and then tests fail):

```
In [1]: import ome_files

In [2]: reader = ome_files.OMETIFFReader()

In [3]: reader.set_id("data/multi-channel-4D-series.companion.ome")
[2017-01-23 16:35:24.024539] [0x00007fff7b936000] [warning] Found invalid TiffData: Z=0, C=1, T=0
[2017-01-23 16:35:24.024570] [0x00007fff7b936000] [warning] Image ID: Image:0 missing plane #5
[2017-01-23 16:35:24.024824] [0x00007fff7b936000] [warning] SizeC mismatch: Channels=1, Pixels=3
```

**Comment by simleo** [comment]
OK, issue fixed in the latest version of your gist. I have updated the test suite accordingly, see 	0afb78a

**Comment by sbesson** [comment]
Tested using one of the superbuild artifacts on CentOS7 release

```
[sbesson@cowfish ~]$ LD_LIBRARY_PATH=${PWD}/ome-files-standalone-bundle-0.2.3-29-gd082225-Release-CentOS7.2-x86_64-b505/lib PYTHONPATH=${PWD}/ome-files-standalone-bundle-0.2.3-29-gd082225-Release-CentOS7.2-x86_64-b505/lib64/python2.7/site-packages python
Python 2.7.5 (default, Sep 15 2016, 22:37:39) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ome_files
>>> reader = ome_files.OMETIFFReader()
>>> reader.set_id('multi-channel-4D-series.ome.tiff')
>>> reader.get_series_count()
1
>>> reader.get_image_count()
105
>>> reader.set_id('multi-channel-4D-series.ome.tiff')
KeyboardInterrupt
>>> reader.close()
>>> reader.set_id('multi-channel-4D-series.ome.tf8')
>>> reader.get_image_count()
105
>>> reader.close()
>>> reader.set_id('tubhiswt-3D/tubhiswt_C0.ome.tif')
>>> reader.get_image_count()
40
>>> reader.close()
>>> reader.set_id('/fc/homes/sbesson/tubhiswt-3D/tubhiswt_C0.ome.tif')
>>> reader.get_used_files()
['/fc/homes/sbesson/tubhiswt-3D/tubhiswt_C0.ome.tif', '/fc/homes/sbesson/tubhiswt-3D/tubhiswt_C1.ome.tif']
>>> reader.open_bytes()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: function takes exactly 1 argument (0 given)
>>> reader.open_bytes(0)
'\x1c\x1b\x1b\x1b\x1d\x1b\x1d\x1c\x1b\x1b\x1a\x1a\x1a\x1a\x1b\x1a\x1a\x19\x19\x1a\x1a\x1a\x19\x18\x1a\x1a\x19\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x1a\x19\x19\x1
...
```

All the API mapped in the current PR seems to work as expected under this minimal testing. in particular the `get_used_files` is returning the expected list.

The unit tests are executed and apssing as expected on the [platform builds](https://ci.openmicroscopy.org/job/OME-FILES-CPP-DEV-merge]. However they fail on the superbuild 
with errors of type

```
[ 90%] Performing test step for 'ome-files-py'
cd /opt/hudson/workspace/OME-FILES-CPP-DEV-merge-superbuild/BUILD_TYPE/Release/node/gretzky35/build/ome-files-py-build && /opt/cmake-3.7.1/bin/cmake -DSOURCE_DIR:PATH=/opt/hudson/workspace/OME-FILES-CPP-DEV-merge-superbuild/BUILD_TYPE/Release/node/gretzky35/ome-files-py -DBUILD_DIR:PATH=/opt/hudson/workspace/OME-FILES-CPP-DEV-merge-superbuild/BUILD_TYPE/Release/node/gretzky35/build/ome-files-py-build -DCONFIG:INTERNAL=Release -DEP_SCRIPT_CONFIG:FILEPATH=/opt/hudson/workspace/OME-FILES-CPP-DEV-merge-superbuild/BUILD_TYPE/Release/node/gretzky35/build/project-config.cmake -P /opt/hudson/workspace/OME-FILES-CPP-DEV-merge-superbuild/BUILD_TYPE/Release/node/gretzky35/superbuild/packages/ome-files-py/test.cmake
test_ometiffreader (unittest.loader.ModuleImportFailure) ... ERROR

======================================================================
ERROR: test_ometiffreader (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_ometiffreader
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/lib64/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/opt/rh/python27/root/usr/lib64/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/opt/hudson/workspace/OME-FILES-CPP-DEV-merge-superbuild/BUILD_TYPE/Release/node/gretzky35/ome-files-py/test/test_ometiffreader.py", line 31, in <module>
    import ome_files
ImportError: No module named ome_files
````

This indicates an environment issue rather than a problem with the tests themselves and can be addressed in a follow-up PR.

Are the `examples` bundled as part of the binaries? Are there immediate next steps to provide a minimal readme/documentation explaining how to use this library?

The questions above should not hold the merging of this PR from my standpoint but rather define the next iterations of this work /cc @joshmoore

**Comment by joshmoore** [comment]
Barring the inclusion of data (which is something that we've repeatedly regretted in other repositories) this looks quite nice. If I had a top wish-list item at this point, it would be a ipynb example which uses `open_bytes` to output (cF. line 5 of https://github.com/IDR/idr-notebooks/blob/master/notebooks/Getting_Started.ipynb). Following that, it would likely be methods for working with annotations, but all of that's *definitely* for later. Very nice!

**Comment by sbesson** [comment]
Re data inclusion, does https://github.com/ome/ome-files-py/pull/2/commits/0afb78aa286836375d70a66c320da64c9e8cb67b someway mitigate the problem (i.e. a single 261K  file and text-only metadata files)? What about force-pushing away/rewriting the commits adding the 8MB OME-TIFF file so that we reduce the impact on the history.

**Comment by joshmoore** [comment]
Certainly better. One 8MB in the history is also not going to be a horrible burden, but certainly something that it's good to decide on upfront.

**Comment by sbesson** [comment]
I concur with @joshmoor there are multiple occassions where we regretted including these big files in the first place. @simleo: thoughts about rewriting the history for the commits adding and removing the large test OME-TIFF? If we want to be extra careful about repo size and history, I pushed two extra commits to https://gist.github.com/sbesson/666bb507580accaccab7b944f1fff243 reducing the plane size to 256x256 plane (67K binary file) or 128x128 (18K binary file) that could be used instead of https://github.com/ome/ome-files-py/pull/2/commits/0afb78aa286836375d70a66c320da64c9e8cb67b

**Comment by simleo** [comment]
* overwritten last commit with a new one where img size is 128 x 64 and pixel type is uint16, so that we could also get rid of `P-TRE_10_R3D_D3D_Z30_C1.ome.tif`, whose only raison d'être was to provide a 2 bpp test case.
* ran `git filter-branch` to purge both `P-TRE_10_R3D_D3D_Z30_C1.ome.tif` and `multi-channel-4D-series.ome.tif` from the whole history

**Comment by simleo** [comment]
@joshmoore re: notebook, how does this look? https://github.com/simleo/ome-files-py/blob/notebook/examples/open_bytes.ipynb

**Comment by joshmoore** [comment]
Very nice!

**Comment by sbesson** [comment]
With the latest commits all builds worked as expected including all unit tests on the platform builds. 💯 Merging to move forward with the next steps (IPython + Docker)

**Pull request merged**
