### PR TITLE
Consume OME Files 0.5 base Docker images

### PR DESCRIPTION
**Pull request by sbesson**
Following the [OME Files 0.5.0 release](http://www.openmicroscopy.org/2017/12/04/ome-files-0-5-0.html), this PR bumps the base images of for the OME Files Python Dockerfile.

### CODE REVIEW

**Comment by joshmoore** [comment]
Nice. A minor point (ha!): I could see using only the 2 digit version but that may not yet be an issue.

**Comment by sbesson** [comment]
As I retrieved the Docker images to push the tags, do you want me to go ahead and just create `0.5` on both fronts?

**Comment by joshmoore** [comment]
That was the process I used on the OMERO side.

**Comment by joshmoore** [comment]
LGTM. `0.2.0` is already tagged. How do we want to represent the relationship?

**Comment by sbesson** [comment]
Not sure this deserves a tag yet at there is infrastructure update-only and there is no new feature since `0.2.0` but if someone feels strongly, I do not mind a `0.2.1`.

**Comment by joshmoore** [comment]
Let's leave it untagged (for the moment) then.

**Pull request merged**
